### PR TITLE
fix: add postal_code_suffix to google maps provider

### LINKED ISSUE #1006: get postal code suffix
i'm using google maps but i do not can get postal code suffix  or ZIP+4

### PR DESCRIPTION
**Pull request by atymic**
The google maps provider is missing the `postal_code_suffix` field as per issue #1006.

This adds the field + test, and fixes some styling issues.

Closes #1006

### CODE REVIEW

File: src/Provider/GoogleMaps/GoogleMaps.php [hunk 1]
```diff
@@ -79,8 +79,14 @@ final class GoogleMaps extends AbstractHttpProvider implements Provider
      *
      * @return GoogleMaps
      */
-    public static function business(HttpClient $client, string $clientId, string $privateKey = null, string $region = null, string $apiKey = null, string $channel = null)
-    {
+    public static function business(
```
Comment (atymic) [inline src/Provider/GoogleMaps/GoogleMaps.php]: Line was too long for PSR2

File: src/Provider/GoogleMaps/GoogleMaps.php [hunk 2]
```diff
@@ -112,7 +118,13 @@ public function geocodeQuery(GeocodeQuery $query): Collection
 
         $url = sprintf(self::GEOCODE_ENDPOINT_URL_SSL, rawurlencode($query->getText()));
         if (null !== $bounds = $query->getBounds()) {
-            $url .= sprintf('&bounds=%s,%s|%s,%s', $bounds->getSouth(), $bounds->getWest(), $bounds->getNorth(), $bounds->getEast());
+            $url .= sprintf(
```
Comment (atymic) [inline src/Provider/GoogleMaps/GoogleMaps.php]: Line was too long for PSR2

File: src/Provider/GoogleMaps/GoogleMaps.php [hunk 3]
```diff
@@ -233,22 +245,24 @@ private function fetchUrl(string $url, string $locale = null, int $limit, string
...
-            $address = $address->withNaturalFeature($builder->getValue('natural_feature'));
-            $address = $address->withAirport($builder->getValue('airport'));
-            $address = $address->withPark($builder->getValue('park'));
-            $address = $address->withPointOfInterest($builder->getValue('point_of_interest'));
-            $address = $address->withEstablishment($builder->getValue('establishment'));
-            $address = $address->withSubLocalityLevels($builder->getValue('subLocalityLevel', []));
-            $address = $address->withPartialMatch($result->partial_match ?? false);
-            $results[] = $address;
+
+            $results[] = $address
```
Comment (atymic) [inline src/Provider/GoogleMaps/GoogleMaps.php]: Switched to chained + added postal code

File: src/Provider/GoogleMaps/Tests/GoogleMapsTest.php [hunk 4]
```diff
@@ -537,6 +537,22 @@ public function testReverseWithSubLocalityLevels()
...
+        $results = $provider->geocodeQuery(GeocodeQuery::create('900 S Oak Park Ave, Oak Park, IL 60304'));
+
+        $this->assertInstanceOf(AddressCollection::class, $results);
+        $this->assertCount(1, $results);
+
+        /** @var GoogleAddress $result */
+        $result = $results->first();
+        $this->assertInstanceOf(Address::class, $result);
+        $this->assertEquals('900 S Oak Park Ave, Oak Park, IL 60304, USA', $result->getFormattedAddress());
+        $this->assertEquals('1936', $result->getPostalCodeSuffix());
```
Comment (jbelien) [inline src/Provider/GoogleMaps/Tests/GoogleMapsTest.php]: I would add this assertion to the other tests so we are sure everything also works fine when `postal_code_suffix` is not set.

Comment (atymic) [reply src/Provider/GoogleMaps/Tests/GoogleMapsTest.php]: Good idea, will do.
